memodir = "/Users/ganariya/memos/_posts"
editor = "vim"
column = 20
width = 0
selectcmd = "peco"
grepcmd = "grep -nH ${PATTERN} ${FILES}"
memotemplate = ""
assetsdir = "."
pluginsdir = "/Users/ganariya/.config/memo/plugins"
templatedirfile = ""
templatebodyfile = ""
